/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [news, setNews] = useState([]);
  useEffect(() => {
    fetch("/data.json")
      .then((res) => res.json())
      .then((data) => {
        setNews(data.data)
        console.log(data.data);
      })
      .catch((err) => console.log(err));
  }, []);
  if(news.length === 0) return <h1>Loading...</h1>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-screen flex bg-black flex-col justify-center items-center">
        <div className="flex justify-center items-center flex-col">
          <h1 className="flex gap-2 text-4xl text-white mt-24">
            Welcome to <p className="text-purple-500">WIDE BLOG</p>
          </h1>
          <img src="AppLogo.png" height={150} width={150} alt="logo" />
        </div>
        {news.map((item, key) => {
          return (
            <div key={key} className="w-screen overflow-hidden p-5 flex flex-col text-center justify-evenly items-center h-56 border-2 border-white rounded-xl mt-5">
              <h1 className="text-3xl uppercase font-semibold text-white">{item.category}</h1>
              <h1 className="text-xl text-gray-200">{item.title}</h1>
            </div>
          )
        })}    
      </main>
    </>
  );
}
